---
address:
  - line: '601 Hillsboro Ave, Apt B'
  - line: 'Edwardsville, IL 62025'
bing_verify: null
collections:
  posts:
    output: true
    title: Posts
  skills:
    output: true
    title: Skills
  uploads:
    output: true
    title: Uploads
color:
  primary: 18bc9c
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
contact: static
credits: '<a href="https://www.flaticon.com/"title="Flaticon">www.flaticon.com</a> <br> <a href="http://startbootstrap.com">Start Bootstrap</a>'
description: Web Development - Data Science - Mobile Development
disqus_shortname: mikepsinn
email: m@crowdsourcingcures.org
exclude:
  - Gemfile.lock
  - node_modules
  - .idea
footer:
  copyright: Mike P. Sinn
  credits: Credits
  location: Location
  social: Around the Web
google_verify: null
keywords: 'quantimodo, think by numbers, web development, business intelligence'
livereload: true
markdown: kramdown
meta_author: Sinn Mike
permalink: pretty
phone: 618-391-0002
port: 4003
general-skills: Web Development - Data Science - Mobile Development
social:
  - title: twitter
    url: 'https://twitter.com/thinkbynumbers'
  - title: facebook
    url: 'https://www.facebook.com/mikepsinn'
  - title: github
    url: 'https://github.com/mikepsinn'
  - title: linkedin
    url: 'https://www.linkedin.com/in/mikesinn/'
  - title: soundcloud
    url: 'https://soundcloud.com/plutonium-kidz'
  - title: youtube
    url: 'https://www.youtube.com/channel/UCO9IkqWQx70wGCxr517Qi4A'
timezone: UTC
title: Mike P. Sinn
url: 'https://mikesinn.com'
libraries:

  -
      
